// -*- mode: ObjC -*-

//  This file is part of class-dump, a utility for examining the Objective-C segment of Mach-O files.
//  Copyright (C) 1997-2019 Steve Nygard.

#import "atlas_CDStructureTable.h"

#import "atlas_CDClassDump.h"
#import "atlas_CDType.h"
#import "atlas_CDTypeController.h"
#import "atlas_CDTypeFormatter.h"
#import "atlas_CDTypeName.h"
#import "atlas_CDStructureInfo.h"

// Phase 0 - This is driven by CDClassDump, registering types from all of the classes, categories, and protocols.
//         - This collects all the top level types (or struct/unions?), keeps a reference count, and flags any that were used in a method.
//         - If a top level struct was used in a method, then the type MUST be declared at the top.
//         - At the end of phase 0, these types are recursively visited, renaming structs whose name starts with $ (like $_12345) to ?, so
//           that we'll treat them as anonymous structures.
//            - Those names must be generated by the compiler.  It can end up with different numbers for the same type.

// Phase 1 - This goes through all the types collected in phase 0, and recursively registers each structure and union with the type controller.
//         - We are not concerned about reference counts or the isUsedInMethod flags.
//         - Since structures and unions can be nested in each other, we need to process each table before doing the end-of-phase work.
//         - We record the maximum structure depth.
//           - Since the deepest union may be buriend in a structure instead of referenced at the top level, we can't calculate the max depth from phase 0.
//           - On the other hand, since we're only interested in the max combined depth of structures and unions, the end result would be the same.
//         - The result of phase 1 is phase1_groupedByDepth: a dictionary keyed by the structure depth, containing arrays of CDStructureInfo.

// Phase 2 - This is driven by CDTypeController.
//         - The goal of phase 2 is to gather member names and types (@"NSObject" vs just @).
//         - It goes through all of the phase1 groups, shallowest to deepest.
//         - For each level group:
//           - First it merges the results of all previous groups with the types at this depth.
//           - Then we group the CDStructureInfos, named structures by name, anon structures by reallyBareTypeString
//             - If they could be combined, the combined CDStructureInfo is to phase2_namedStructureInfo or phase2_anonStructureInfo.
//             - If they couldn't be combined, the uncombined CDStructureInfos are added to phase2_nameExceptions or phase2_anonExceptions.

// Phase 3 - Using all of the information available from the merged types from phase 2, we merge these types with the types from phase 0
//           to fill in missing member names, and the occasional object type.

// After all the phases are done, typedef names are generated for all anonymous structures, and then field names are added for missing fields.
//  - bitfields don't need to have a name, so they can be blank.
//  - the typedef name is calculated from a hash of the typeString.
//    - Doing it before adding missing fields means we could change the field names without changing the typedef name.
//    - Makes the name independant of the order they were encountered (like the previous indexes were).  You can get meaningful diffs between
//      framework changes now.

static BOOL atlas_debug = NO;
static BOOL atlas_debugNamedStructures = NO;
static BOOL atlas_debugAnonStructures = NO;

@interface ObjCAtlasStructureTable ()
@end

#pragma mark -

@implementation ObjCAtlasStructureTable
{
    __weak ObjCAtlasTypeController *atlas__typeController;
    
    NSString *atlas__identifier;
    NSString *atlas__anonymousBaseName;
    
    // Phase 0 - top level
    NSMutableDictionary *atlas__phase0_structureInfo; // key: NSString (typeString), value: CDStructureInfo
    
    // Phase 1 - all substructures
    NSMutableDictionary *atlas__phase1_structureInfo; // key: NSString (typeString), value: CDStructureInfo
    NSUInteger atlas__phase1_maxDepth;
    NSMutableDictionary *atlas__phase1_groupedByDepth; // key: NSNumber (structureDepth), value: NSMutableArray of CDStructureInfo
    
    // Phase 2 - merging all structure bottom up
    NSMutableDictionary *atlas__phase2_namedStructureInfo; // key: NSString (name), value: CDStructureInfo
    NSMutableDictionary *atlas__phase2_anonStructureInfo; // key: NSString (reallyBareTypeString), value: CDStructureInfo
    NSMutableArray *atlas__phase2_nameExceptions; // Of CDStructureInfo
    NSMutableArray *atlas__phase2_anonExceptions; // Of CDStructureInfo
    
    // Phase 3 - merged reference counts from updated phase0 types
    NSMutableDictionary *atlas__phase3_namedStructureInfo; // key: NSString (name), value: CDStructureInfo
    NSMutableDictionary *atlas__phase3_anonStructureInfo; // key: NSString (reallyBareTypeString), value: CDStructureInfo
    
    NSMutableDictionary *atlas__phase3_nameExceptions; // key: NSString (typeString), value: CDStructureInfo
    NSMutableDictionary *atlas__phase3_anonExceptions; // key: NSString (typeString), value: CDStructureInfo
    
    NSMutableSet *atlas__phase3_exceptionalNames; // Of NSString
    NSMutableSet *atlas__phase3_inMethodNameExceptions; // Of NSString
    
    BOOL atlas__shouldDebug;
    
    NSMutableSet *atlas__debugNames; // NSString (name)
    NSMutableSet *atlas__debugAnon; // NSString (reallyBareTypeString)
}

// Preserve the original explicit property storage after renaming.
@synthesize identifier = atlas__identifier;
@synthesize atlas_anonymousBaseName = atlas__anonymousBaseName;
@synthesize atlas_shouldDebug = atlas__shouldDebug;
@synthesize atlas_typeController = atlas__typeController;
@synthesize atlas_phase1_maxDepth = atlas__phase1_maxDepth;

- (id)init;
{
    if ((self = [super init])) {
        atlas__identifier = nil;
        atlas__anonymousBaseName = nil;
        
        atlas__phase0_structureInfo = [[NSMutableDictionary alloc] init];
        
        atlas__phase1_structureInfo = [[NSMutableDictionary alloc] init];
        atlas__phase1_maxDepth = 0;
        atlas__phase1_groupedByDepth = [[NSMutableDictionary alloc] init];
        
        atlas__phase2_namedStructureInfo = [[NSMutableDictionary alloc] init];
        atlas__phase2_anonStructureInfo = [[NSMutableDictionary alloc] init];
        atlas__phase2_nameExceptions = [[NSMutableArray alloc] init];
        atlas__phase2_anonExceptions = [[NSMutableArray alloc] init];
        
        atlas__phase3_namedStructureInfo = [[NSMutableDictionary alloc] init];
        atlas__phase3_anonStructureInfo = [[NSMutableDictionary alloc] init];
        atlas__phase3_nameExceptions = [[NSMutableDictionary alloc] init];
        atlas__phase3_anonExceptions = [[NSMutableDictionary alloc] init];
        
        atlas__phase3_exceptionalNames = [[NSMutableSet alloc] init];
        atlas__phase3_inMethodNameExceptions = [[NSMutableSet alloc] init];
        
        atlas__shouldDebug = NO;
        
        atlas__debugNames = [[NSMutableSet alloc] init];
        atlas__debugAnon = [[NSMutableSet alloc] init];
    }

    return self;
}

#pragma mark - Phase 0

- (void)atlas_phase0RegisterStructure:(ObjCAtlasType *)atlas_structure atlas_usedInMethod:(BOOL)atlas_isUsedInMethod;
{
    NSString *atlas_key = atlas_structure.atlas_typeString;
    ObjCAtlasStructureInfo *atlas_info = atlas__phase0_structureInfo[atlas_key];
    if (atlas_info == nil) {
        atlas_info = [[ObjCAtlasStructureInfo alloc] initAtlasWithType:atlas_structure];
        if (atlas_isUsedInMethod)
            atlas_info.atlas_isUsedInMethod = YES;
        atlas__phase0_structureInfo[atlas_key] = atlas_info;
    } else {
        [atlas_info atlas_addReferenceCount:1];
        if (atlas_isUsedInMethod)
            atlas_info.atlas_isUsedInMethod = YES;
    }
}

- (void)atlas_finishPhase0;
{
    if (atlas_debug) NSLog(@"[%@] %s, changing struct names that start with $", self.identifier, atlas___cmd);
    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase0_structureInfo allValues]) {
        [atlas_info.type atlas_phase0RecursivelyFixStructureNames:atlas_debug];
    }

    if ([atlas__debugNames count] > 0) {
        NSLog(@"======================================================================");
        NSLog(@"[%@] %s", self.identifier, atlas___cmd);
        NSLog(@"debug names: %@", [[atlas__debugNames allObjects] componentsJoinedByString:@", "]);
        for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase0_structureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
            if ([atlas__debugNames containsObject:[atlas_info.type.atlas_typeName description]])
                NSLog(@"%@", [atlas_info atlas_shortDescription]);
        }
        NSLog(@"======================================================================");
    }

    if ([atlas__debugAnon count] > 0) {
        NSLog(@"======================================================================");
        NSLog(@"[%@] %s", self.identifier, atlas___cmd);
        NSLog(@"debug anon: %@", [[atlas__debugAnon allObjects] componentsJoinedByString:@", "]);
        for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase0_structureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
            if ([atlas__debugAnon containsObject:atlas_info.type.atlas_reallyBareTypeString])
                NSLog(@"%@", [atlas_info atlas_shortDescription]);
        }
        NSLog(@"======================================================================");
    }
}

#pragma mark - Phase 1

- (void)atlas_runPhase1;
{
    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase0_structureInfo allValues]) {
        [atlas_info.type atlas_phase1RegisterStructuresWithObject:self.atlas_typeController];
    }
}

// Need to gather all of the structures, since some substructures may have member names we'd otherwise miss.
- (void)atlas_phase1RegisterStructure:(ObjCAtlasType *)atlas_structure;
{
    NSString *atlas_key = atlas_structure.atlas_typeString;
    ObjCAtlasStructureInfo *atlas_info = atlas__phase1_structureInfo[atlas_key];
    if (atlas_info == nil) {
        atlas_info = [[ObjCAtlasStructureInfo alloc] initAtlasWithType:atlas_structure];
        atlas__phase1_structureInfo[atlas_key] = atlas_info;
    }
}

// Need to merge names bottom-up to catch cases like: {?=@@iiffff{_NSRect={_NSPoint=ff}{_NSSize=ff}}{?=b1b1b1b1b1b27}}

- (void)atlas_finishPhase1;
{
    if (atlas_debug) {
        NSLog(@"======================================================================");
        NSLog(@"[%@] %s", self.identifier, atlas___cmd);
    }

    // The deepest union may not be at the top level (buried in a structure instead), so need to get the depth here.
    // But we'll take the max of structure and union depths in the CDTypeController anyway.

    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase1_structureInfo allValues]) {
        NSUInteger atlas_depth = atlas_info.type.atlas_structureDepth;
        if (atlas__phase1_maxDepth < atlas_depth)
            atlas__phase1_maxDepth = atlas_depth;
    }
    if (atlas_debug) NSLog(@"[%@] Maximum structure depth is: %lu", self.identifier, atlas__phase1_maxDepth);

    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase1_structureInfo allValues]) {
        NSNumber *atlas_key = [NSNumber numberWithUnsignedInteger:atlas_info.type.atlas_structureDepth];
        NSMutableArray *atlas_group = atlas__phase1_groupedByDepth[atlas_key];
        if (atlas_group == nil) {
            atlas_group = [[NSMutableArray alloc] init];
            [atlas_group addObject:atlas_info];
            atlas__phase1_groupedByDepth[atlas_key] = atlas_group;
        } else {
            [atlas_group addObject:atlas_info];
        }
    }

    if (atlas_debug) NSLog(@"depth groups: %@", [[atlas__phase1_groupedByDepth allKeys] sortedArrayUsingSelector:@selector(compare:)]);
}

- (NSUInteger)atlas_phase1_maxDepth;
{
    return atlas__phase1_maxDepth;
}

#pragma mark - Phase 2

// From lowest to highest depths:
// - Go through all infos at that level
//   - recursively (bottom up) try to merge substructures into that type, to get names/full types
// - merge all mergeable infos at that level

- (void)atlas_runPhase2AtDepth:(NSUInteger)atlas_depth;
{
    //NSLog(@"[%@] %s, depth: %u", identifier, __cmd, depth);
    NSNumber *atlas_depthKey = [NSNumber numberWithUnsignedInteger:atlas_depth];
    NSArray *atlas_infos = atlas__phase1_groupedByDepth[atlas_depthKey];

    for (ObjCAtlasStructureInfo *atlas_info in atlas_infos) {
        // recursively (bottom up) try to merge substructures into that type, to get names/full types
        //NSLog(@"----------------------------------------");
        //NSLog(@"Trying phase2Merge with on %@", [[info type] typeString]);
        [atlas_info.type atlas_phase2MergeWithTypeController:self.atlas_typeController atlas_debug:atlas_debug];
    }

    // merge all mergeable infos at that level
    NSMutableDictionary *atlas_nameDict = [NSMutableDictionary dictionary];
    NSMutableDictionary *atlas_anonDict = [NSMutableDictionary dictionary];

    // Group named structures by name.
    // Group anon structures by reallyBareTypeString.
    for (ObjCAtlasStructureInfo *atlas_info in atlas_infos) {
        NSString *atlas_name = [atlas_info.type.atlas_typeName description];

        if ([@"?" isEqualToString:atlas_name]) {
            NSString *atlas_key = atlas_info.type.atlas_reallyBareTypeString;
            NSMutableArray *atlas_group = atlas_anonDict[atlas_key];
            if (atlas_group == nil) {
                atlas_group = [[NSMutableArray alloc] init];
                [atlas_group addObject:atlas_info];
                atlas_anonDict[atlas_key] = atlas_group;
            } else {
                [atlas_group addObject:atlas_info];
            }
        } else {
            NSMutableArray *atlas_group = atlas_nameDict[atlas_name];
            if (atlas_group == nil) {
                atlas_group = [[NSMutableArray alloc] init];
                [atlas_group addObject:atlas_info];
                atlas_nameDict[atlas_name] = atlas_group;
            } else {
                [atlas_group addObject:atlas_info];
            }
        }
    }

    // Now... for each group, make sure we can combine them all together.
    // If not, this means that either the types or the member names conflicted, and we save the entire group as an exception.
    for (NSString *atlas_key in [atlas_nameDict allKeys]) {
        ObjCAtlasStructureInfo *atlas_combined = nil;

        //NSLog(@"key... %@", key);
        NSMutableArray *atlas_group = atlas_nameDict[atlas_key];
        for (ObjCAtlasStructureInfo *atlas_info in atlas_group) {
            if (atlas_combined == nil) {
                atlas_combined = [atlas_info copy];
            } else {
                //NSLog(@"old: %@", [[combined type] typeString]);
                //NSLog(@"new: %@", [[info type] typeString]);
                if ([atlas_combined.type atlas_canMergeWithType:atlas_info.type]) {
                    [atlas_combined.type atlas_mergeWithType:atlas_info.type];
                    [atlas_combined atlas_addReferenceCount:atlas_info.atlas_referenceCount];
#if 0
                    if (info.isUsedInMethod)
                        combined.isUsedInMethod = YES;
#endif
                } else {
                    atlas_combined = nil;
                    break;
                }
            }
        }

        if (atlas_combined != nil) {
            ObjCAtlasStructureInfo *atlas_previousInfo = atlas__phase2_namedStructureInfo[atlas_key];
            if (atlas_previousInfo != nil) {
                // struct _Vector_impl in HALLab.
                [atlas__phase2_nameExceptions addObject:atlas_previousInfo];
                //[phase2_nameExceptions addObjectsFromArray:group]; // Or just add the combined?
                [atlas__phase2_nameExceptions addObject:atlas_combined];
                [atlas__phase2_namedStructureInfo removeObjectForKey:atlas_key];
                if (atlas_debugNamedStructures) {
                    NSLog(@"[%@] %s, WARNING: depth %lu name %@ has conflict(?) at lower level", self.identifier, atlas___cmd, atlas_depth, atlas_key);
                    NSLog(@"previous: %@", [atlas__phase2_namedStructureInfo[atlas_key] atlas_shortDescription]);
                    NSLog(@" current: %@", [atlas_combined atlas_shortDescription]);
                }
            } else {
                atlas__phase2_namedStructureInfo[atlas_key] = atlas_combined;
            }
        } else {
            if (atlas_debugNamedStructures) {
                NSLog(@"----------------------------------------");
                NSLog(@"Can't be combined: %@", atlas_key);
                NSLog(@"group: %@", atlas_group);
            }
            [atlas__phase2_nameExceptions addObjectsFromArray:atlas_group];
        }
    }

    //NSLog(@"======================================================================");
    for (NSString *atlas_key in [atlas_anonDict allKeys]) {
        ObjCAtlasStructureInfo *atlas_combined = nil;

        //NSLog(@"key... %@", key);
        NSMutableArray *atlas_group = atlas_anonDict[atlas_key];
        for (ObjCAtlasStructureInfo *atlas_info in atlas_group) {
            if (atlas_combined == nil) {
                atlas_combined = [atlas_info copy];
                //NSLog(@"info: %@", [info shortDescription]);
                //NSLog(@"combined: %@", [combined shortDescription]);
            } else {
                //NSLog(@"old: %@", [combined shortDescription]);
                //NSLog(@"new: %@", [info shortDescription]);
                if ([atlas_combined.type atlas_canMergeWithType:atlas_info.type]) {
                    [atlas_combined.type atlas_mergeWithType:atlas_info.type];
                    [atlas_combined atlas_addReferenceCount:atlas_info.atlas_referenceCount];
#if 0
                    if (info.isUsedInMethod)
                        combined.isUsedInMethod = YES;
#endif
                } else {
                    if (atlas_debugAnonStructures) {
                        NSLog(@"previous: %@", atlas_combined.type.atlas_typeString);
                        NSLog(@"    This: %@", atlas_info.type.atlas_typeString);
                    }
                    atlas_combined = nil;
                    break;
                }
            }
        }

        if (atlas_combined != nil) {
            if (atlas__phase2_anonStructureInfo[atlas_key] != nil) {
                // This shouldn't happen, but the named case might.
                NSLog(@"[%@] %s, WARNING: depth %lu type %@ has conflict(?) at lower level", self.identifier, atlas___cmd, atlas_depth, atlas_key);
                NSLog(@"previous: %@", [atlas__phase2_anonStructureInfo[atlas_key] atlas_shortDescription]);
                NSLog(@" current: %@", [atlas_combined atlas_shortDescription]);
            }
            atlas__phase2_anonStructureInfo[atlas_key] = atlas_combined;
        } else {
            if (atlas_debugAnonStructures) {
                NSLog(@"----------------------------------------");
                NSLog(@"Can't be combined: %@", atlas_key);
                NSLog(@"group: %@", atlas_group);
            }
            [atlas__phase2_anonExceptions addObjectsFromArray:atlas_group];
        }
    }
}

- (ObjCAtlasType *)atlas_phase2ReplacementForType:(ObjCAtlasType *)atlas_type;
{
    NSString *atlas_name = [atlas_type.atlas_typeName description];
    ObjCAtlasStructureInfo *atlas_info;

    if ([@"?" isEqualToString:atlas_name]) {
        atlas_info = atlas__phase2_anonStructureInfo[atlas_type.atlas_reallyBareTypeString];
    } else {
        atlas_info = atlas__phase2_namedStructureInfo[atlas_name];
    }

    return atlas_info.type;
}

- (void)atlas_finishPhase2;
{
    if ([atlas__debugNames count] > 0) {
        NSLog(@"======================================================================");
        NSLog(@"[%@] %s", self.identifier, atlas___cmd);
        NSLog(@"debug names: %@", [[atlas__debugNames allObjects] componentsJoinedByString:@", "]);
        for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase2_namedStructureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
            if ([atlas__debugNames containsObject:[atlas_info.type.atlas_typeName description]])
                NSLog(@"%@", [atlas_info atlas_shortDescription]);
        }
        NSLog(@"======================================================================");
    }

    if ([atlas__debugAnon count] > 0) {
        NSLog(@"======================================================================");
        NSLog(@"[%@] %s", self.identifier, atlas___cmd);
        NSLog(@"debug anon: %@", [[atlas__debugAnon allObjects] componentsJoinedByString:@", "]);
        for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase2_anonStructureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
            if ([atlas__debugAnon containsObject:atlas_info.type.atlas_reallyBareTypeString])
                NSLog(@"%@", [atlas_info atlas_shortDescription]);
        }
        NSLog(@"======================================================================");
    }

    //[self logPhase2Info];
}

#pragma mark - Phase 3

- (void)atlas_phase2ReplacementOnPhase0;
{
    if (atlas_debug) {
        NSLog(@"======================================================================");
        NSLog(@"[%@]  > %s", self.identifier, atlas___cmd);
    }

    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase0_structureInfo allValues]) {
        [atlas_info.type atlas_phase2MergeWithTypeController:self.atlas_typeController atlas_debug:atlas_debug];
    }

    if (atlas_debug) NSLog(@"[%@] <  %s", self.identifier, atlas___cmd);
}

// Go through all updated phase0_structureInfo types
// - start merging these into a new table
//   - If this is the first time a structure has been added:
//     - add one reference for each subtype
//   - otherwise just merge them.
// - end result should be CDStructureInfos with counts and method reference flags

- (void)atlas_buildPhase3Exceptions;
{
    for (ObjCAtlasStructureInfo *atlas_info in atlas__phase2_nameExceptions) {
        ObjCAtlasStructureInfo *atlas_newInfo = [atlas_info copy];
        atlas_newInfo.atlas_referenceCount = 0;
        atlas_newInfo.atlas_isUsedInMethod = NO;
        atlas__phase3_nameExceptions[atlas_newInfo.type.atlas_typeString] = atlas_newInfo;
        [atlas__phase3_exceptionalNames addObject:atlas_newInfo.name];
    }

    for (ObjCAtlasStructureInfo *atlas_info in atlas__phase2_anonExceptions) {
        ObjCAtlasStructureInfo *atlas_newInfo = [atlas_info copy];
        atlas_newInfo.atlas_referenceCount = 0;
        atlas_newInfo.atlas_isUsedInMethod = NO;
        atlas__phase3_anonExceptions[atlas_newInfo.type.atlas_typeString] = atlas_newInfo;
    }

    //NSLog(@"phase3 name exceptions: %@", [[phase3_nameExceptions allKeys] componentsJoinedByString:@", "]);
    //NSLog(@"phase3 anon exceptions: %@", [[phase3_anonExceptions allKeys] componentsJoinedByString:@"\n"]);
    //exit(99);
}

- (void)atlas_runPhase3;
{
    //NSLog(@"[%@]  > %s", identifier, __cmd);

    for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase0_structureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
        [self atlas_phase3RegisterStructure:atlas_info.type atlas_count:atlas_info.atlas_referenceCount atlas_usedInMethod:atlas_info.atlas_isUsedInMethod];
    }

    //NSLog(@"[%@] <  %s", identifier, __cmd);
}

- (void)atlas_phase3RegisterStructure:(ObjCAtlasType *)atlas_structure
                          atlas_count:(NSUInteger)atlas_referenceCount
                   atlas_usedInMethod:(BOOL)atlas_isUsedInMethod
{
    //NSLog(@"[%@]  > %s", identifier, __cmd);

    NSString *atlas_name = [atlas_structure.atlas_typeName description];
    if ([@"?" isEqualToString:atlas_name]) {
        NSString *atlas_key = atlas_structure.atlas_reallyBareTypeString;
        //NSLog(@"key: %@, isUsedInMethod: %u", key, isUsedInMethod);
        ObjCAtlasStructureInfo *atlas_info = atlas__phase3_anonExceptions[atlas_structure.atlas_typeString];
        if (atlas_info != nil) {
            if (atlas_debugAnonStructures) NSLog(@"%s, anon key %@ has exception from phase 2", atlas___cmd, atlas_structure.atlas_typeString);
            [atlas_info atlas_addReferenceCount:atlas_referenceCount];
            if (atlas_isUsedInMethod)
                atlas_info.atlas_isUsedInMethod = YES;

            if (atlas_info.atlas_referenceCount == atlas_referenceCount) { // i.e. the first time we've encounter this struct
                // And then... add 1 reference for each substructure, stopping recursion when we've encountered a previous structure
                [atlas_structure atlas_phase3RegisterMembersWithTypeController:self.atlas_typeController];
            }
        } else {
            atlas_info = atlas__phase3_anonStructureInfo[atlas_key];
            if (atlas_info == nil) {
                atlas_info = [[ObjCAtlasStructureInfo alloc] initAtlasWithType:atlas_structure];
                [atlas_info setAtlas_referenceCount:atlas_referenceCount];
                if (atlas_isUsedInMethod)
                    atlas_info.atlas_isUsedInMethod = YES;
                atlas__phase3_anonStructureInfo[atlas_key] = atlas_info;

                // And then... add 1 reference for each substructure, stopping recursion when we've encountered a previous structure
                [atlas_structure atlas_phase3RegisterMembersWithTypeController:self.atlas_typeController];
            } else {
                [atlas_info atlas_addReferenceCount:atlas_referenceCount];
                if (atlas_isUsedInMethod)
                    atlas_info.atlas_isUsedInMethod = YES;
            }
        }
    } else {
        if ([atlas__debugNames containsObject:atlas_name]) NSLog(@"[%@] %s, type= %@", self.identifier, atlas___cmd, atlas_structure.atlas_typeString);
        //NSLog(@"[%@] %s, name: %@", identifier, __cmd, name);
        if ([atlas__phase3_exceptionalNames containsObject:atlas_name]) {
            if (atlas_debugNamedStructures) NSLog(@"%s, name %@ has exception from phase 2", atlas___cmd, atlas_name);
            ObjCAtlasStructureInfo *atlas_info = atlas__phase3_nameExceptions[atlas_structure.atlas_typeString];
            // Info can be nil.  For example, from {_CommandStackEntry}
            if (atlas_info != nil) {
                [atlas_info atlas_addReferenceCount:atlas_referenceCount];
                if (atlas_isUsedInMethod)
                    [atlas__phase3_inMethodNameExceptions addObject:atlas_name];

                if (atlas_info.atlas_referenceCount == atlas_referenceCount) { // i.e. the first time we've encounter this struct
                    // And then... add 1 reference for each substructure, stopping recursion when we've encountered a previous structure
                    [atlas_structure atlas_phase3RegisterMembersWithTypeController:self.atlas_typeController];
                }
            }
        } else {
            ObjCAtlasStructureInfo *atlas_info = atlas__phase3_namedStructureInfo[atlas_name];
            if (atlas_info == nil) {
                if ([atlas__debugNames containsObject:atlas_name]) NSLog(@"[%@] %s, info was nil for %@", self.identifier, atlas___cmd, atlas_name);
                atlas_info = [[ObjCAtlasStructureInfo alloc] initAtlasWithType:atlas_structure];
                [atlas_info setAtlas_referenceCount:atlas_referenceCount];
                if (atlas_isUsedInMethod)
                    atlas_info.atlas_isUsedInMethod = YES;
                atlas__phase3_namedStructureInfo[atlas_name] = atlas_info;

                // And then... add 1 reference for each substructure, stopping recursion when we've encountered a previous structure
                [atlas_structure atlas_phase3RegisterMembersWithTypeController:self.atlas_typeController];
            } else {
                if ([atlas__debugNames containsObject:atlas_name]) NSLog(@"[%@] %s, info before: %@", self.identifier, atlas___cmd, [atlas_info atlas_shortDescription]);
                // Handle the case where {foo} occurs before {foo=iii}
                if ([atlas_info.type.atlas_members count] == 0) {
                    [atlas_info.type atlas_mergeWithType:atlas_structure];

                    // And then... add 1 reference for each substructure, stopping recursion when we've encountered a previous structure
                    [atlas_structure atlas_phase3RegisterMembersWithTypeController:self.atlas_typeController];
                }
                [atlas_info atlas_addReferenceCount:atlas_referenceCount];
                if (atlas_isUsedInMethod)
                    atlas_info.atlas_isUsedInMethod = YES;
                if ([atlas__debugNames containsObject:atlas_name]) {
                    NSLog(@"[%@] %s, added ref count: %lu, isUsedInMethod: %u", self.identifier, atlas___cmd, atlas_referenceCount, atlas_isUsedInMethod);
                    NSLog(@"[%@] %s, info after: %@", self.identifier, atlas___cmd, [atlas_info atlas_shortDescription]);
                }
            }
        }
    }

    //NSLog(@"[%@] <  %s", identifier, __cmd);
}

- (void)atlas_finishPhase3;
{
    if ([atlas__debugNames count] > 0) {
        NSLog(@"======================================================================");
        NSLog(@"[%@] %s", self.identifier, atlas___cmd);
        NSLog(@"names: %@", [[atlas__debugNames allObjects] componentsJoinedByString:@", "]);
        for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase3_namedStructureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
            if ([atlas__debugNames containsObject:[atlas_info.type.atlas_typeName description]])
                NSLog(@"%@", [atlas_info atlas_shortDescription]);
        }
        for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase3_nameExceptions allValues]) {
            if ([atlas__debugNames containsObject:[atlas_info name]])
                NSLog(@"%@ is in the name exceptions", atlas_info.name);
        }
        NSLog(@"======================================================================");
    }

    if ([atlas__debugAnon count] > 0) {
        NSLog(@"======================================================================");
        NSLog(@"[%@] %s", self.identifier, atlas___cmd);
        NSLog(@"debug anon: %@", [[atlas__debugAnon allObjects] componentsJoinedByString:@", "]);
        for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase3_anonStructureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
            if ([atlas__debugAnon containsObject:atlas_info.type.atlas_reallyBareTypeString])
                NSLog(@"%@", [atlas_info atlas_shortDescription]);
        }
        for (NSString *atlas_str in atlas__debugAnon)
            if (atlas__phase3_anonExceptions[atlas_str] != nil)
                NSLog(@"%@ is in the anon exceptions", atlas_str);
        NSLog(@"======================================================================");
    }

    //[self logPhase3Info];
}

- (ObjCAtlasType *)atlas_phase3ReplacementForType:(ObjCAtlasType *)atlas_type;
{
    NSString *atlas_name = [atlas_type.atlas_typeName description];
    ObjCAtlasStructureInfo *atlas_info;
    
    if ([@"?" isEqualToString:atlas_name]) {
        atlas_info = atlas__phase3_anonStructureInfo[atlas_type.atlas_reallyBareTypeString];
    } else {
        atlas_info = atlas__phase3_namedStructureInfo[atlas_name];
    }

    return atlas_info.type;
}

#pragma mark - Other

- (void)atlas_generateTypedefNames;
{
    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase3_anonStructureInfo allValues]) {
        [atlas_info atlas_generateTypedefName:self.atlas_anonymousBaseName];
    }
    
    // And do the same for each of the anon exceptions
    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase3_anonExceptions allValues]) {
        [atlas_info atlas_generateTypedefName:self.atlas_anonymousBaseName];
    }
    
    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase3_nameExceptions allValues]) {
        [atlas_info atlas_generateTypedefName:[NSString stringWithFormat:@"%@_", atlas_info.type.atlas_typeName.name]];
        atlas_info.type.atlas_typeName.name = @"?";
    }
    
    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase3_namedStructureInfo allValues]) {
        if (atlas_info.type.atlas_isTemplateType && atlas_info.atlas_isUsedInMethod) {
            [atlas_info atlas_generateTypedefName:[NSString stringWithFormat:@"%@_", atlas_info.type.atlas_typeName.name]];
        }
    }
}

- (void)atlas_generateMemberNames;
{
    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase3_namedStructureInfo allValues]) {
        [atlas_info.type atlas_generateMemberNames];
    }
    
    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase3_anonStructureInfo allValues]) {
        [atlas_info.type atlas_generateMemberNames];
    }
    
    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase3_nameExceptions allValues]) {
        [atlas_info.type atlas_generateMemberNames];
    }
    
    // And do the same for each of the anon exceptions
    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase3_anonExceptions allValues]) {
        [atlas_info.type atlas_generateMemberNames];
    }
}

// TODO: (2003-12-23) Add option to show/hide this section
// TODO: (2003-12-23) sort by name or by dependency
// TODO: (2003-12-23) declare in modules where they were first used

- (void)atlas_appendNamedStructuresToString:(NSMutableString *)atlas_resultString
                            atlas_formatter:(ObjCAtlasTypeFormatter *)atlas_typeFormatter
                             atlas_markName:(NSString *)atlas_markName;
{
    BOOL atlas_hasAddedMark = NO;
    BOOL atlas_hasShownExceptions = NO;

    for (NSString *atlas_key in [[atlas__phase3_namedStructureInfo allKeys] sortedArrayUsingSelector:@selector(compare:)]) {
        ObjCAtlasStructureInfo *atlas_info = atlas__phase3_namedStructureInfo[atlas_key];
        BOOL atlas_shouldShow = ![self atlas_shouldExpandStructureInfo:atlas_info];
        if (atlas_shouldShow || atlas_debugNamedStructures) {
            if (atlas_hasAddedMark == NO) {
                [atlas_resultString appendFormat:@"#pragma mark %@\n\n", atlas_markName];
                atlas_hasAddedMark = YES;
            }

            ObjCAtlasType *atlas_type = atlas_info.type;
            if ([atlas_typeFormatter.atlas_typeController atlas_shouldShowName:[atlas_type.atlas_typeName description]]) {
                if (atlas_debugNamedStructures) {
                    [atlas_resultString appendFormat:@"// would normally show? %u\n", atlas_shouldShow];
                    [atlas_resultString appendFormat:@"// depth: %lu, ref count: %lu, used in method? %u\n", atlas_info.type.atlas_structureDepth, atlas_info.atlas_referenceCount, atlas_info.atlas_isUsedInMethod];
                }
                NSString *atlas_formattedString = [atlas_typeFormatter atlas_formatVariable:nil atlas_type:atlas_type];
                if (atlas_formattedString != nil) {
                    [atlas_resultString appendString:atlas_formattedString];
                    [atlas_resultString appendString:@";\n\n"];
                }
            }
        }
    }

    for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase3_nameExceptions allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
        BOOL atlas_shouldShow = ![self atlas_shouldExpandStructureInfo:atlas_info];
        if (atlas_shouldShow || atlas_debugNamedStructures) {
            if (atlas_hasAddedMark == NO) {
                [atlas_resultString appendFormat:@"#pragma mark %@\n\n", atlas_markName];
                atlas_hasAddedMark = YES;
            }

            if (atlas_hasShownExceptions == NO) {
                [atlas_resultString appendString:@"#if 0\n"];
                [atlas_resultString appendString:@"// Names with conflicting types:\n"];
                atlas_hasShownExceptions = YES;
            }

            ObjCAtlasType *atlas_type = atlas_info.type;
            if ([atlas_typeFormatter.atlas_typeController atlas_shouldShowName:[atlas_type.atlas_typeName description]]) {
                if (atlas_debugNamedStructures) {
                    [atlas_resultString appendFormat:@"// depth: %lu, ref count: %lu, used in method? %u\n", atlas_info.type.atlas_structureDepth, atlas_info.atlas_referenceCount, atlas_info.atlas_isUsedInMethod];
                    //[resultString appendFormat:@"// typedefName: %@\n", [info typedefName]];
                }
                NSString *atlas_formattedString = [atlas_typeFormatter atlas_formatVariable:nil atlas_type:atlas_type];
                if (atlas_formattedString != nil) {
                    [atlas_resultString appendFormat:@"typedef %@ %@;\n\n", atlas_formattedString, atlas_info.atlas_typedefName];
                }
            }
        }
    }
    if (atlas_hasShownExceptions)
        [atlas_resultString appendString:@"#endif\n\n"];

    if (atlas_debugNamedStructures) {
        [atlas_resultString appendString:@"\n// Name exceptions:\n"];
        for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase3_nameExceptions allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)])
            [atlas_resultString appendFormat:@"// %@\n", [atlas_info atlas_shortDescription]];
        [atlas_resultString appendString:@"\n"];
    }
}

- (void)atlas_appendTypedefsToString:(NSMutableString *)atlas_resultString
                     atlas_formatter:(ObjCAtlasTypeFormatter *)atlas_typeFormatter
                      atlas_markName:(NSString *)atlas_markName;
{
    BOOL atlas_hasAddedMark = NO;
    BOOL atlas_hasShownExceptions = NO;

    for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase3_anonStructureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
        BOOL atlas_shouldShow = ![self atlas_shouldExpandStructureInfo:atlas_info];
        if (atlas_shouldShow || atlas_debugAnonStructures) {
            if (atlas_hasAddedMark == NO) {
                [atlas_resultString appendFormat:@"#pragma mark %@\n\n", atlas_markName];
                atlas_hasAddedMark = YES;
            }

            if (atlas_debugAnonStructures) {
                [atlas_resultString appendFormat:@"// would normally show? %u\n", atlas_shouldShow];
                [atlas_resultString appendFormat:@"// %@\n", atlas_info.type.atlas_reallyBareTypeString];
                [atlas_resultString appendFormat:@"// depth: %lu, ref: %lu, used in method? %u\n", atlas_info.type.atlas_structureDepth, atlas_info.atlas_referenceCount, atlas_info.atlas_isUsedInMethod];
            }

            NSString *atlas_formattedString = [atlas_typeFormatter atlas_formatVariable:nil atlas_type:atlas_info.type];
            if (atlas_formattedString != nil) {
                [atlas_resultString appendFormat:@"typedef %@ %@;\n\n", atlas_formattedString, atlas_info.atlas_typedefName];
            }
        }
    }

    // TODO: (2009-08-25) Need same ref count rules for anon exceptions.
    for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase3_anonExceptions allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
        BOOL atlas_shouldShow = ![self atlas_shouldExpandStructureInfo:atlas_info];
        if (atlas_shouldShow || atlas_debugAnonStructures) {
            if (atlas_hasAddedMark == NO) {
                [atlas_resultString appendFormat:@"#pragma mark %@\n\n", atlas_markName];
                atlas_hasAddedMark = YES;
            }

            if (atlas_hasShownExceptions == NO) {
                [atlas_resultString appendString:@"// Ambiguous groups\n"];
                atlas_hasShownExceptions = YES;
            }

            if (atlas_debugAnonStructures) {
                [atlas_resultString appendFormat:@"// %@\n", atlas_info.type.atlas_reallyBareTypeString];
                [atlas_resultString appendFormat:@"// depth: %lu, ref: %lu, used in method? %u\n", atlas_info.type.atlas_structureDepth, atlas_info.atlas_referenceCount, atlas_info.atlas_isUsedInMethod];
            }

            NSString *atlas_formattedString = [atlas_typeFormatter atlas_formatVariable:nil atlas_type:atlas_info.type];
            if (atlas_formattedString != nil) {
                //[resultString appendFormat:@"%@;\n\n", formattedString];
                [atlas_resultString appendFormat:@"typedef %@ %@;\n\n", atlas_formattedString, atlas_info.atlas_typedefName];
            }
        }
    }

    for (NSString *atlas_key in [[atlas__phase3_namedStructureInfo allKeys] sortedArrayUsingSelector:@selector(compare:)]) {
        ObjCAtlasStructureInfo *atlas_info = atlas__phase3_namedStructureInfo[atlas_key];
        BOOL atlas_shouldShow = atlas_info.type.atlas_isTemplateType && atlas_info.atlas_isUsedInMethod;
        if (atlas_shouldShow || atlas_debugAnonStructures) {
            if (atlas_hasAddedMark == NO) {
                [atlas_resultString appendFormat:@"#pragma mark %@\n\n", atlas_markName];
                atlas_hasAddedMark = YES;
            }

            if (atlas_hasShownExceptions == NO) {
                [atlas_resultString appendString:@"// Template types\n"];
                atlas_hasShownExceptions = YES;
            }

            if (atlas_debugAnonStructures) {
                [atlas_resultString appendFormat:@"// %@\n", atlas_info.type.atlas_reallyBareTypeString];
                [atlas_resultString appendFormat:@"// depth: %lu, ref: %lu, used in method? %u\n", atlas_info.type.atlas_structureDepth, atlas_info.atlas_referenceCount, atlas_info.atlas_isUsedInMethod];
            }

            NSString *atlas_formattedString = [atlas_typeFormatter atlas_formatVariable:nil atlas_type:atlas_info.type];
            if (atlas_formattedString != nil) {
                //[resultString appendFormat:@"%@;\n\n", formattedString];
                [atlas_resultString appendFormat:@"typedef %@ %@;\n\n", atlas_formattedString, atlas_info.atlas_typedefName];
            }
        }
    }
}

- (BOOL)atlas_shouldExpandStructureInfo:(ObjCAtlasStructureInfo *)atlas_info;
{
    return (atlas_info == nil)
        || (atlas_info.atlas_isUsedInMethod == NO
            && (atlas_info.type.atlas_isTemplateType == NO || atlas_info.atlas_isUsedInMethod == NO)
            && atlas_info.atlas_referenceCount < 2
            && (([atlas_info.name hasPrefix:@"_"] && [atlas_info.name atlas_hasUnderscoreCapitalPrefix] == NO) // TODO: Don't need the first hasPrefix check now.
                || [@"?" isEqualToString:atlas_info.name]));
}

// For automatic expansion?
- (BOOL)atlas_shouldExpandType:(ObjCAtlasType *)atlas_type;
{
    ObjCAtlasStructureInfo *atlas_info;
    NSString *atlas_name = [atlas_type.atlas_typeName description];
    if ([@"?" isEqualToString:atlas_name]) {
        NSString *atlas_key = atlas_type.atlas_reallyBareTypeString;
        atlas_info = atlas__phase3_anonStructureInfo[atlas_key];
        if (atlas_info == nil) {
            // Look for an exception
            atlas_info = atlas__phase3_anonExceptions[atlas_type.atlas_typeString];
        }
    } else {
        atlas_info = atlas__phase3_namedStructureInfo[atlas_name];
        if (atlas_info == nil) {
            atlas_info = atlas__phase3_nameExceptions[atlas_type.atlas_typeString];
            if (atlas_info != nil) {
                //NSLog(@"[%@] %s, found phase3 name exception... %@", identifier, __cmd, [info shortDescription]);
                //return NO;
            }
        }
    }

    return [self atlas_shouldExpandStructureInfo:atlas_info];
}

- (NSString *)atlas_typedefNameForType:(ObjCAtlasType *)atlas_type;
{
    ObjCAtlasStructureInfo *atlas_info = atlas__phase3_anonStructureInfo[atlas_type.atlas_reallyBareTypeString];
    if (atlas_info == nil) {
        atlas_info = atlas__phase3_anonExceptions[atlas_type.atlas_typeString];
        //NSLog(@"fallback typedef info? %@ -- %@", [info shortDescription], info.typedefName);
    }

    if (atlas_info == nil) {
        // Check name exceptions
        atlas_info = atlas__phase3_nameExceptions[atlas_type.atlas_typeString];
#if 0
        if (info != nil)
            NSLog(@"Got typedef name for phase3 name exception: %@", info.typedefName);
#endif
    }

    if (atlas_info == nil) {
        atlas_info = atlas__phase3_namedStructureInfo[[atlas_type.atlas_typeName description]];
    }
#if 0
    if (type.isTemplateType && info.typedefName == nil) {
        NSLog(@"Warning: no typedef name for type: %@", type.typeString);
    }
#endif

    return atlas_info.atlas_typedefName;
}

#pragma mark -

- (void)atlas_debugName:(NSString *)atlas_name;
{
    [atlas__debugNames addObject:atlas_name];
}

- (void)atlas_debugAnon:(NSString *)atlas_str;
{
    [atlas__debugAnon addObject:atlas_str];
}

- (void)atlas_logPhase0Info;
{
    NSLog(@"======================================================================");
    NSLog(@"[%@] %s", self.identifier, atlas___cmd);
    for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase0_structureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
        NSLog(@"%@", [atlas_info atlas_shortDescription]);
    }
    NSLog(@"======================================================================");
}

- (void)atlas_logPhase2Info;
{
#if 0
    NSLog(@"======================================================================");
    NSLog(@"[%@] %s, named:", identifier, atlas___cmd);
    for (CDStructureInfo *info in [[phase2_namedStructureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
        NSLog(@"%@", [info shortDescription]);
    }
#endif
#if 0
    NSLog(@"======================================================================");
    NSLog(@"[%@] %s, anon:", identifier, atlas___cmd);
    for (CDStructureInfo *info in [[phase2_anonStructureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
        NSLog(@"%@", [info shortDescription]);
    }
#endif
#if 1
    NSLog(@"======================================================================");
    NSLog(@"[%@] %s, named exceptions:", self.identifier, atlas___cmd);
    for (ObjCAtlasStructureInfo *atlas_info in [atlas__phase2_nameExceptions sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
        NSLog(@"%@", [atlas_info atlas_shortDescription]);
    }
#endif
#if 0
    NSLog(@"======================================================================");
    NSLog(@"[%@] %s, anon exceptions:", identifier, atlas___cmd);
    for (CDStructureInfo *info in [phase2_anonExceptions sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
        NSLog(@"%@", [info shortDescription]);
    }
#endif
}

- (void)atlas_logPhase3Info;
{
    NSLog(@"[%@]  > %s", self.identifier, atlas___cmd);
#if 0
    NSLog(@"----------------------------------------------------------------------");
    NSLog(@"named:");
    for (NSString *name in [[phase3_namedStructureInfo allKeys] sortedArrayUsingSelector:@selector(compare:)]) {
        CDStructureInfo *info = phase3_namedStructureInfo[name];
        NSLog(@"%@", [info shortDescription]);
    }
    
    NSLog(@"----------------------------------------------------------------------");
    NSLog(@"anon:");
    for (CDStructureInfo *info in [[phase3_anonStructureInfo allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
        NSLog(@"%@", [info shortDescription]);
    }
#endif
    NSLog(@"======================================================================");
    NSLog(@"[%@] %s, anon exceptions:", self.identifier, atlas___cmd);
    for (ObjCAtlasStructureInfo *atlas_info in [[atlas__phase3_anonExceptions allValues] sortedArrayUsingSelector:@selector(ascendingCompareByStructureDepth:)]) {
        NSLog(@"%@", [atlas_info atlas_shortDescription]);
    }
    
    NSLog(@"[%@] <  %s", self.identifier, atlas___cmd);
}

@end
